[MIG] Migration to v11 (#11)
* [ADD] Initial commit. Import from extra-addons.

* [ADD] Initial commit. Import from extra-addons.

* [IMP] cleanup

* [IMP] cleanup

* [FIX] Comment training_hr dependency. res.partner.job has been removed and is used by the training modules.

* [IMP] [#9439] Added a mgmtsystem.system object in the demo data.

* [FIX] [#9604] Added the mail module as a dependency

* [FIX] [#9604] Replaced mailgate.message with mail.message.

* [FIX] [#9604] Replaced the references to the fields nameds that have changed.

TODO: Re-implement the same functionality level with the new API.

* [FIX] Reference to quality manual

* [FIX] group_mgmtsystem_manager XML ID
[IMP] mgmtsystem_kpi

* [FIX] Group references. Reported by michaelgiesbrecht on the forum.

* [ADD] Icons

* [ADD] Icons

* [IMP] Move audittrail dependency from mgmtsystem to requiring modules

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* CHG: marking Apps, security review, translation pt, finetuning

* [ADD] Move wiki_quality_manual from lp:openobject-addons/6.1 to document_page_quality_manual

* [FIX[ licenses and dependencies

* [FIX[ licenses and dependencies

* [IMP] Update hooks with addons modules from v7

* [IMP] Update hooks with addons modules from v7

* [CHG] AGPL license; set verion to 1.0

* [CHG] AGPL license; set verion to 1.0

* [FIX] .py files licenses to AGPL

* [FIX] .py files licenses to AGPL

* [CHG] Updated view XMLs for OpenERP 7.0

At first, I thought I could replace what seemed to be a copy/paste of the crm.claim form view from OpenERP 6.1 by an inherited view that simply adds the reference field, but after much messing around, I always ended up with a messed up form view, so I had to resort to copy/pasting OpenERP 7.0's form view for crm.claim and add a reference field to it.

I've also removed two menu items which seemed to do nothing more than what their corresponding menu items are doing in crm.claim (and they caused errors on install).

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* [CHG] Changed MediaWiki syntax in document pages to plain HTML.

document_page doesn't seem to support MediaWiki syntax anymore.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* [CHG] Making audit trail rules an option. They will be automatically installed if the audittrail module is installed.

* [CHG] Making audit trail rules an option. They will be automatically installed if the audittrail module is installed.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* [FIX[ Migration folder names

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* [FIX] crm.claim.stage access rights

* [FIX] Integrity Error with reference

* [FIX] lp:1169784

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* label Poplicy n'est pas au bonne endroit

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* [REN] Renaming pot files

* [UPG] module manifest and views to v7 format

* [UPG] module manifest and views to v7 format

* [UPG] module manifest and views to v7 format

* [IMP] Add company_id and its default value

* [IMP] Add company_id and its default value

* [IMP] Add company_id in views

* [IMP] Add company_id in views

* [FIX] Missing object : review_line

* [ADD] mgmtsystem_*_security.xml files

* [FIX] PEP8 compliance after running flake8

* [FIX] PEP8 compliance after running flake8

* [FIX] PEP8 compliance after running flake8

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Adding migration script for quality manual for OpenUpgrade

* Adding migration script for work instructions for OpenUpgrade

* [FIX] Migration scripts no longer fully dependent on openupgrade

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Removed redundant import from openupgrade

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Init 8.0 branch

* Init 8.0 branch

* Init 8.0 branch

* Moved document_page_quality_manual to root folder for port

* Making installable is enough, nothing to port

* Moved mgmtsystem_review to root folder
Fix imports and replaced survey.responses by survey.user_input
Removed vim lines
[IMP] Add README.rst and data, views and models directories
Remove executable flag on python files and xml
Moved icon
[IMP] - mgmtsystem_review: Improved view and fixed typo.
[ADD] - mgmtsystem_review: Updated pot and added spanish translation.
[FIX] - mgmtsystem_review: Fixed translation template.
[REM] Migration files
[IMP] Description, version
[IMP] Add "Try me" button
[IMP] Remove osv
[FIX] Formatting in README.rst
[FIX] import models
[IMP] Migrate to new API
[FIX] AttributeError: 'module' object has no attribute 'Many2Many'
[FIX] Trailing comma after field definition

* Migrate mgmtsystem_quality

* [IMP] Add README.rst and data directory

* Moved icon and reformatted manifest

* Add bug tracker link on README.rst

* OCA Transbot updated translations from Transifex

* OCA Transbot updated translations from Transifex

* [UPD] prefix versions with 8.0

* [MIG] Make modules uninstallable

* [MIG] Make modules uninstallable

* [MIG] Make modules uninstallable

* Migration of document_page_quality_manual to Odoo 9.0

[IMP] Update the structure to ISO 9001:2015

* Update README.rst

* MgmtSystem migration to odoo 9 progress

* MgmtSystem Quality migration to Odoo 9.0

* All contributors added

* maxime email corrected

* Applying maxime recommendations

* Improving module

* adding Add Item to surveys form tree

* Review report is Ok Now

* [IMP] Contributors

* OCA Transbot updated translations from Transifex

* [FIX] remove en.po that was erroneously created by transbot

* OCA Transbot updated translations from Transifex

* [MIG] Make modules uninstallable

* [MIG] Make modules uninstallable

* [MIG] Make modules uninstallable

* [MIG] Rename manifest files

* [MIG] Rename manifest files

* [MIG] Rename manifest files

* MIG document_page_quality_manual to V. 10.0

MIG document_page_quality_manual to V. 10.0

* MIG mgmtsystem_review to V. 10.0

* OCA Transbot updated translations from Transifex

* MIG mgmtsystem_quality to v. 10.0

* OCA Transbot updated translations from Transifex

* [FIX] Added specific tree view for res users with create=1 and delete=1 to allow users selection on review

* OCA Transbot updated translations from Transifex

* OCA Transbot updated translations from Transifex

* remove obsolete .pot files [ci skip]

* remove obsolete .pot files [ci skip]

* remove obsolete .pot files [ci skip]

* [UPD] Update document_page_quality_manual.pot

* [UPD] Update mgmtsystem_quality.pot

* [UPD] Update mgmtsystem_review.pot

* [MIG] mgmtsystem_review: migration to v11

* [MIG] mgmtsystem_action: migration to v11

* bump modules to v11

* [MIG] mgmtsystem_quality

* [MIG] document_page_quality_manual: migration to v11

* [MIG] mgmtsystem_audit: remove automated actions

* [FIX] mgmtsystem_action: fix lint C8107(translation-required)

* [ADD] Initial commit. Import from extra-addons.

* [ADD] Icons

* CHG: qualification fields moved from feedback to NC; actions can be linked to projects

* ADD: option to relate a NC to a Contract / Analytic Account

* CHG: added parent to group NC Causes; removed NC Category

* CHG: small fixes and finetuning

* CHG: marking Apps, security review, translation pt, finetuning

* [FIX] fixes from review comments

* [FIX] missing context; instanciation of models

* [CHG] AGPL license; set verion to 1.0

* [CHG] Selections use words instead of letters; fixed AGPL-3 reference

* [FIX] .py files licenses to AGPL

* [UPD] POT files

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* [UPG] module manifest and views to v7 format

* Launchpad automatic translations update.

* [ADD] mgmtsystem_*_security.xml files

* [FIX] PEP8 compliance after running flake8

* [FIX] PEP8 compliance after running flake8

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* [FIX] Fix PEP8 errors after running 'flake8 . --ignore E501,F401'

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Launchpad automatic translations update.

* Init 8.0 branch

* Init 8.0 branch

* Moved mgmtsystem_claim from __unported__

* Ported mgmtsystem_claim to API 8.0

There are some problems with state to stage_id that can't be that
easily ported

* Updated code to v8 and fixed syntax errors (flake8)

* Moved icon to static/description

* Fix model and added tests

* Fixed access right for files and reformat __openerp__

* Reformatted and removed comments

* Added stages to claims

* Moved files in folders

* Updated code with menus and removed useless attributes in views

* Added back a state

* Added back colors

* Added back states as stages

* Colors for stages...

doesn't seem to work

* Reformat workflow

* Fix flake error

* Replaced old email action by the new with template

* Added claim stage security rule for users

* Slovene translations added

* OCA Transbot updated translations from Transifex

* [UPD] prefix versions with 8.0

* [MOV] move addons out of __unported__ (they remain not installable)

* [MIG] Make modules uninstallable

* [MIG] Make modules uninstallable

* [ADD][mgmtsystem_nonconformity_report]Added 8Ds Analysis Report. (#3)

Init module that generate the nonconformity report.
 This report is generated by each nonconformity

* [FIX] remove en.po that was erroneously created by transbot

* [MIG] Rename manifest files

* [MIG] Rename manifest files

* remove obsolete .pot files [ci skip]

* remove obsolete .pot files [ci skip]

* [MIG] mgmtsystem_claim: Migration to v11

* [MIG] mgmtsystem_nonconformity_project: migration to v11

* [MIG] mgmtsystem_nonconformity_report: migration to v11

* [FIX] pylint

* [IMP] mgmtsystem_manual: fix es.po translations

* [IMP] mgmtsystem_noncanformity: change position of immediate action